# Generated by Django 5.1.8 on 2025-04-29 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_school_school_type'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='name',
            new_name='school_name',
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('school', 'school_name')},
        ),
    ]
