# Generated by Django 5.1.8 on 2025-04-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_school_school_type'),
        ('students', '0002_rename_name_class_school_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='school_name',
            new_name='class_name',
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('school', 'class_name')},
        ),
    ]
