# Generated by Django 5.1.8 on 2025-05-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_school_name_class_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='custom_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='custom_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
