# Generated by Django 5.1.8 on 2025-04-24 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255, unique=True)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('school_type', models.CharField(choices=[('nursery_school', 'Nursery_school'), ('primary_school', 'Primary_school'), ('secondary_school', 'Secondary_school'), ('nursery,_primary_school', 'Nursery,_primary_school'), ('nursery,_primary,_secondary_school', 'Nursery,_primary,_secondary_school')], default='nursery school', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
