# Generated by Django 5.1.8 on 2025-04-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('nursery school', 'Nursery school'), ('primary school', 'Primary school'), ('secondary school', 'Secondary school'), ('nursery, primary school', 'Nursery, primary school'), ('nursery, primary, secondary school', 'Nursery, primary, secondary school')], default='nursery school', max_length=100),
        ),
    ]
