# Generated by Django 5.1.8 on 2025-05-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_school_school_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='custom_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
